=== Nitin-Xebia/Training/SOA-WebServices/Sample-Projects/Web-Services/Xml_demo/Schema/complexTypeComposite/po.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="purchaseOrder" type="PurchaseOrderType"/>
	  <xsd:element name="comment" type="xsd:string"/>
	 <xsd:complexType name="PurchaseOrderType">
		<xsd:sequence>
			<xsd:element name="shipTo" type="USAddress"/>
			<xsd:element name="billTo" type="USAddress"/>
			<xsd:element ref="comment" minOccurs="0"/>
			<xsd:element name="items" type="Items"/>
		</xsd:sequence>
		<xsd:attribute name="orderDate" type="xsd:date"/>
	</xsd:complexType>
	<xsd:complexType name="USAddress">
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string"/>
			<xsd:element name="street" type="xsd:string"/>
			<xsd:element name="city" type="xsd:string"/>
			<xsd:element name="state" type="xsd:string"/>
			<xsd:element name="zip" type="xsd:decimal"/>
		</xsd:sequence>
		<xsd:attribute name="country" type="xsd:NMTOKEN" fixed="US"/>
	</xsd:complexType>
	<xsd:complexType name="Items">
		 <xsd:sequence>
			   <xsd:element name="item" type="xsd:string" maxOccurs="unbounded"/>				 
		  </xsd:sequence>
	</xsd:complexType>	 
</xsd:schema>

=== Nitin-Xebia/Training/SOA-WebServices/Sample-Projects/Web-Services/Xml_demo/Schema/complexTypeComposite/po.xml
<?xml version="1.0"?>
<purchaseOrder orderDate="1999-10-20" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="po.xsd">
	<shipTo country="US">
		<name>Bill Gates</name>
		<street>123 Redmonds</street>
		<city>California</city>
		<state>WS</state>
		<zip>12345</zip>
	</shipTo>
	<billTo country="US"><!--Can it be  =UK ?-->
		<name>Robert Smith</name>
		<street>8 Oak Avenue</street>
		<city>Cambridge</city>
		<state>MA</state>
		<zip>12345</zip>
	</billTo>
	<items>
		<item></item>		 
		<item ></item> 		 
	</items>
</purchaseOrder>
