=== Nitin-Xebia/Training/SOA-WebServices/Sample-Projects/Web-Services/Xml_demo/DTD/factory.dtd
<?xml version='1.0' encoding='us-ascii'?>

 

<!ELEMENT Factory (Unit,UnitBreak)+>
<!ATTLIST Factory 
            title    CDATA    #REQUIRED >

<!ELEMENT Unit ANY >

<!ELEMENT UnitBreak EMPTY >

<!ATTLIST Unit type   CDATA   #REQUIRED >

<!ELEMENT title (#PCDATA)>
<!ELEMENT training (#PCDATA)>

<!ENTITY   % slogan "#PCDATA"> <!-- Make it export-->
 
<!ELEMENT Transport (#PCDATA)>
<!ELEMENT Paragraph (#PCDATA|Line|Letter|Word)*>
<!ELEMENT Line (#PCDATA)>
<!ELEMENT Letter (#PCDATA)>
<!ELEMENT Word   (#PCDATA)>
<!ELEMENT caption (#PCDATA)>

=== Nitin-Xebia/Training/SOA-WebServices/Sample-Projects/XML-Processor/DTD/FactoryEntityUse.xml
<?xml version="1.0" encoding="utf-8"?>


<!DOCTYPE Factory SYSTEM "factory.dtd" [
  <!ENTITY product  "MatchBox">
  <!ENTITY vehicle "Metador">
  <!ENTITY cars "Marutis">
  <!ENTITY CopyRight SYSTEM "copyright.xml">

]> 
<!--The entities declared above are general entities-->

   <Factory title="&product; Manufacturing">

    <Unit type = "Production"> 
      <title>Start Production for 100 &product;!</title>
      <training>How to make the &product;</training> 	  
	  </Unit>   
      <UnitBreak/>

    <Unit type="Marketing">
        <title> Marketing</title> 
        <caption>Who will buy the &product; ?</caption> 
		<Paragraph>
		  First make the Brouchure for &product;
		  <Line>Then visit the prospective buyers</Line> 
		  <!--slogan>Follow up with the Letters</slogan--> 
		  <Word>Say Thank You to the Customers!</Word> 
          &CopyRight;
		</Paragraph>
    </Unit>
     <UnitBreak/>
	 <!--UnitBreak></UnitBreak-->


   <Unit type="Dispatch">
        <title>Forwarding</title> 
        <Transport>Which &vehicle; will be used ?</Transport> 
    </Unit>
	<UnitBreak/>
</Factory>

<!--Validate with Parser nad run with EchoParser to disply the contents and see the product and vehicle replacements-->
