<!--?xml version='1.0' encoding='us-ascii'?-->

 
<!--Internal dtd slideInternalDtd.xml  -->

<!DOCTYPE slideshow [
<!ELEMENT slideshow (slide)+>
<!ELEMENT slide (title, item*)>
<!ELEMENT title (#PCDATA)> 
<!--ELEMENT item (#PCDATA)-->
<!ELEMENT item (#PCDATA | item)*>
]>

<slideshow>
    <slide>     
      <title>Overview</title>
      <item>This is xml intro</item>       
      <item>XML is defined by IETF</item>
    </slide>
    <slide>     
      <title>XML Usage</title>
      <item>XML is used to define data</item>       
      <item>XML is is used to send data information
	      <item>XML is powerfull</item> 
		  <item>XML is for dataDefintiion</item>  
		  XML is really cool..
	  </item>
    </slide>
</slideshow>
