=== Nitin-Xebia/Training/SOA-WebServices/Sample-Projects/Web-Services/Xml_demo/DTD/slide0.dtd
<!--
    DTD for a simple "slide0 show".
-->
 
<!ELEMENT slideshow (slide)*>
<!ELEMENT slide (title, item*,price)>

<!ELEMENT title (#PCDATA)>
<!ELEMENT item (#PCDATA) >
<!ELEMENT price (#PCDATA) >

=== Nitin-Xebia/Training/SOA-WebServices/Sample-Projects/Web-Services/Xml_demo/DTD/userSlides.xml
<?xml version='1.0' encoding='us-ascii'?>

 

<!DOCTYPE slideshow SYSTEM "slide0.dtd">

<slideshow>
    <slide>     
      <title>user &amp; me</title>
      
      <item>This is xml intro</item>       
      <item>XML is defined by IETF</item>
      <price>
          344 &lt; 78
  
         <![CDATA[2345 < 1000]]>
</price>
    </slide>   
    
    <slide>     
      <title>MyData</title>
      <item>This is java intro</item>       
      <!--<item>XML is defined by IETF</item>-->
       <price>2444</price>
      
    </slide>       
</slideshow>

=== Nitin-Xebia/Training/SOA-WebServices/Sample-Projects/XML-Processor/DTD/slide0.xml
<?xml version='1.0' encoding='us-ascii'?>

 

<!DOCTYPE slideshow SYSTEM "slide0.dtd">

<slideshow>
    <slide>     
      <title>Overview</title>
      
      <item>This is xml intro</item>       
      <item>XML is defined by IETF</item>
      <price>2223</price>
    </slide>   
    
    <slide>     
      <title>Intro</title>
      <item>This is java intro</item>       
      <!--<item>XML is defined by IETF</item>-->
       <price>2444</price>
      
    </slide>       
</slideshow>
