=== Nitin-Xebia/Training/SOA-WebServices/Sample-Projects/Web-Services/Xml_demo/DTD/slide2.dtd
<?xml version='1.0' encoding='us-ascii'?>

 <!-- Steffy is default value for author -->

<!ELEMENT slideshow (slide+)>
<!ATTLIST slideshow 
            show    CDATA    #REQUIRED
            date     CDATA    #IMPLIED
            author   CDATA    "Steffy"  
>
<!ELEMENT slide (image?, title, item*)>
<!ATTLIST slide 
            type   (play | demo | all) #IMPLIED
>
<!ELEMENT title (#PCDATA)>
<!ELEMENT item (#PCDATA | item)* >
<!ELEMENT image EMPTY>  
<!ATTLIST image 
            graphicSupport    CDATA    #IMPLIED
            src               CDATA    #REQUIRED
            type              CDATA    "image/gif"
>

<!--EMPTY means the element contains neither text nor child elements and even comment tags are not allowed-->

=== Nitin-Xebia/Training/SOA-WebServices/Sample-Projects/Web-Services/Xml_demo/DTD/Slide21.xml
<!DOCTYPE slideshow SYSTEM "slide2.dtd">  
 

 
<slideshow 
    show="Great Tennis Show"
    date="Date of publication"
    author="Andre Agassi"
    >

    <!-- PROCESSING INSTRUCTION -->
    <?my.presentation.Program QUERY="play, demo, all"?>
	<!--Parser specific information -->
	<!--a colon can conflict with namespace declaration-->

    <!-- Title slide without image and item -->
    <slide type="demo">
       <title>Wake up to Sampras!</title>
    </slide>

    <!-- Tennis Overview-->
    <slide type="all">
      <title>Tennis Overview</title>
      <item>
	      Why the game of 
		  <item>Tennis </item>
		   is Great ?
		 </item>
      <item/>
      <item>Who <item>buys</item>Tickets for Wimbeldon ?</item>
    </slide>
 </slideshow>

=== Nitin-Xebia/Training/SOA-WebServices/Sample-Projects/XML-Processor/DTD/slide2.xml
<!--?xml version='1.0' encoding='us-ascii'?-->

 

<!DOCTYPE slideshow SYSTEM "slide2.dtd">  
 

 
<slideshow 
    show="Great Tennis Show"  
    author="Andre & bAgassi"
    >

    <!-- PROCESSING INSTRUCTION -->
    <?my.presentation.Program QUERY="play, demo, all"?>
	<!--Parser specific information -->
	<!--a colon can conflict with namespace declaration-->

    <!-- Title slide without image and item -->
    <slide type="data">
       <title>Wake up to Sampras!</title>
    </slide>

    <!-- Tennis Overview-->
    <slide type="all">
      <title>Tennis Overview</title>
      <item>
	      Why the game of 
		  <item>Tennis </item>
		   is Great ?
		 </item>
      <item/>
      <item>Who <item>buys</item>Tickets for Wimbeldon ?</item>
    </slide>

    <slide type="demo">
      <title>Tennis Forecast</title>
	  <item>Actual Score</item>
      <item>Becker Score < predicted!</item>
      
      <item>Expected Revenues</item>
      <item>Total Collection</item>
    </slide>


    <slide type="demo">
	  <image src = "c:\data\show.gif">
	  	 <myData>sfhsfsd</myData>
	  	</image>	   
      <title>NewYork OpenTennis</title>

      <item>Andre Score > predicted!</item>
	  <!--using the character Entity Ref-->
	  <!--Run with EchoParser and see the &gt replaced value-->

      <item>Actual Score</item>       
      <item>Total Collection</item>
	  <!--image src = "c:\data\show.gif"/--><!--It cannot be defined here  see the sequence in dtd -->	   
    </slide>

    <slide type="play">
      <title>How to play Tennis ?</title>
      <item>First I start the service</item>
      <item>Then I try to kick it off</item>
      <item>Finally, he is won...</item>
      <item><![CDATA[ScoreBoard:
                         
           Becker <--------------------Andre
               |            <3>        ^
               | <1>                   |   <1> = lo
               V                       |   <2> = draw    
             status--------------------+   <3> = frenzie play
                            <2>
      ]]></item>
    </slide>
</slideshow>

=== Nitin-Xebia/Training/SOA-WebServices/Sample-Projects/Web-Services/Xml_demo/DTD/slideCharEntities.xml
<!--?xml version='1.0' encoding='us-ascii'?-->

 

<!DOCTYPE slideshow SYSTEM "slide2.dtd">  
 

 
<slideshow 
    show="Great Tennis Show"
    date="Date of publication"
    author="Andre Agassi"
    >
   
<!--donot pass author attribute and run with EchoParser to see the defualt value of steffy for author displayed-->
    <slide type="demo">
      <title>Tennis > It works! as Forecasted</title>
	   <!--This willnot raise error since it doesnot define opening tag like
	   like < to contain other items-->
	  <!--Putting  < will generate error even if the title is of CDATA type
	  Try putting &lt; here -->
	  <item>Actual Score</item>
      <item>Becker Score > predicted!</item>      
	 
      <item>Expected Revenues</item>
      <item>Total Collection</item>
    </slide>


    <slide type="demo">
	  <image src = "c:\data\show.gif"/>	   
      <title>NewYork OpenTennis</title>

	  <item>Andre Score &lt; predicted</item>

      <!--item>Andre Score < predicted</item-->
	  <!--This will raise error -->
	  <!--using the character Entity Ref-->
	  <!--Run with EchoParser and see the &gt replaced value-->

      <item>Actual Score</item>       
      <item>Total Collection</item>
	  <!--image src = "c:\data\show.gif"/--><!--It cannot be defined here  see the sequence in dtd -->	   
    </slide>
 
</slideshow>

=== Nitin-Xebia/Training/SOA-WebServices/Sample-Projects/Web-Services/Xml_demo/DTD/slide2bad.xml
<?xml version='1.0' encoding='us-ascii'?>

<!-- Slides with a error -->

<!DOCTYPE slideshow SYSTEM "slide2.dtd">  
 

<slideshow 
    show="My Slide Show"
    date="Date of publication"
    author="Yours Truly"
    >

    <!-- TITLE SLIDE -->
    <slide type="all">
      <title>Wake up to Error!</title>
    </slide>

    <!-- OVERVIEW -->
    <slide type="all">
      <title>Overview</title>
      <item>Why <em>Widgets</em> are great</item>       
      <item>Who buys Widgets?</item>
    </slide>

</slideshow>
