=== Nitin-Xebia/Training/SOA-WebServices/Sample-Projects/XML-Processor/Schema/ComplexWithinRoot/Dept.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema">
	<element name="Dept">
		<complexType>
			<sequence>
				<element name="Person" minOccurs="1" maxOccurs="3">
					<complexType>
						<sequence>
							<element name="FirstName" type="string"/>
							<element name="Grade" type="positiveInteger"/>
							<element name="Type" type="string"/>
						</sequence>
					</complexType>
				</element>
			</sequence>
		</complexType>
	</element>
</schema>

=== Nitin-Xebia/Training/SOA-WebServices/Sample-Projects/XML-Processor/Schema/Dept.xml
<?xml version="1.0" encoding="UTF-8"?>
<Dept xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Dept.xsd">
	<Person>
		<Type>Strong</Type>
		<FirstName>Boss</FirstName>
		<Grade>9</Grade>		
	</Person>
	<Person>
		<FirstName>Manager</FirstName>		
		<Type>SubOrdinate</Type>
		<Grade>6</Grade>
	</Person>
</Dept>
