=== Nitin-Xebia/Training/SOA-WebServices/Sample-Projects/XML-Processor/Schema/ComplexExtend/travel.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	    targetNamespace="http://example.org" 
            xmlns:e="http://example.org">
            
<!-- type derivation hierarchy

             TravelType
             /     |    \
     PlaneType AutoType  TrainType
-->  

<xsd:complexType name="TravelType">  
  <xsd:sequence>
    <xsd:element name="origin" type="xsd:string"/>
    <xsd:element name="destination" type="xsd:string"/>
  </xsd:sequence>
</xsd:complexType>
<xsd:complexType name="PlaneType">  
  <xsd:complexContent>
    <xsd:extension base="e:TravelType">
      <xsd:sequence>
        <xsd:element name="flightNumber" type="xsd:int"/>
        <xsd:element name="meal" type="xsd:string"/>
      </xsd:sequence>
   </xsd:extension>
  </xsd:complexContent>
</xsd:complexType>

<xsd:complexType name="AutoType">   
  <xsd:complexContent>
    <xsd:extension base="e:TravelType">
      <xsd:sequence>
       <xsd:element name="rentalAgency" type="e:RentalCompany"/>
       <xsd:element name="ratePerHour" type="xsd:int"/>
      </xsd:sequence>
    </xsd:extension>
  </xsd:complexContent>
</xsd:complexType>
<xsd:complexType name="TrainType">  
  <xsd:complexContent>
    <xsd:extension base="e:TravelType">
     <xsd:sequence>
       <xsd:element name="track" type="xsd:int"/>
       <xsd:element name="dailyScheduleNumber" type="xsd:int"/>
     </xsd:sequence>
    </xsd:extension>
  </xsd:complexContent>
</xsd:complexType>

<xsd:simpleType name="RentalCompany">
    <xsd:restriction base="xsd:NCName">
      <xsd:enumeration value="Avis"/>
      <xsd:enumeration value="Hertz"/>
      <xsd:enumeration value="RentAWreck"/>
    </xsd:restriction>
</xsd:simpleType>

<!-- Create the substitution group with head element "e:travel". -->

<xsd:element name="travel" type="e:TravelType"/>
<xsd:element name="plane" type="e:PlaneType" 
             substitutionGroup="e:travel"/>
<xsd:element name="auto" type="e:AutoType"
	     substitutionGroup="e:travel"/>
<xsd:element name="train" type="e:TrainType"
	     substitutionGroup="e:travel"/>

<xsd:element name="TravelMode">
  <xsd:complexType> 
    <xsd:sequence>
      <xsd:element ref="e:travel" maxOccurs="unbounded"/>      
    </xsd:sequence>
  </xsd:complexType>
</xsd:element>
</xsd:schema>

=== Nitin-Xebia/Training/SOA-WebServices/Sample-Projects/Web-Services/Xml_demo/Schema/ComplexExtend/travel.xml
<?xml version="1.0"?>
<e:TravelMode xmlns:e="http://example.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://example.org travel.xsd">
	<e:plane>
		<origin>BOSTON</origin>
		<destination>SAN FRANCISCO</destination>
		<flightNumber>195</flightNumber>
		<meal>breakfast</meal>
	</e:plane>
	<e:auto>
		<origin>SAN FRANCISCO</origin>
		<destination>SAN FRANCISCO</destination>
		<rentalAgency>Hertz</rentalAgency>
		<ratePerHour>2</ratePerHour>
	</e:auto>
	<e:train>
		<origin>BOSTON</origin>
		<destination>NEW YORK</destination>
		<track>9</track>
		<dailyScheduleNumber>805</dailyScheduleNumber>
	</e:train>
	 
</e:TravelMode>
