=== Nitin-Xebia/Training/SOA-WebServices/Sample-Projects/Web-Services/Xml_demo/Schema/anyDemo/any.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" >
<xs:element name="Types">
          <xs:complexType>
			<xs:sequence>
				<xs:element ref="DataType" maxOccurs="unbounded"/>			 
			</xs:sequence>
		</xs:complexType>
	</xs:element> 
	
	<xs:element name="DataType">
		<xs:complexType>
			<xs:sequence>
			<xs:any minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		</xs:complexType>
	</xs:element>	
	<xs:element name="Variable" type="xs:QName"/>
	<xs:element name="Data" type="xs:string"/>
	<xs:element name="Number" type="xs:int"/>
	 
</xs:schema>

=== Nitin-Xebia/Training/SOA-WebServices/Sample-Projects/Web-Services/Xml_demo/Schema/anyDemo/any.xml
<?xml version="1.0" encoding="UTF-8"?>
<Types xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="any.xsd">
	<DataType>
	   <Data>myData</Data>
	</DataType>
	
    <DataType>
      <Number>3</Number>
      <Data>NotYet</Data>
	</DataType>
	
	<DataType>
	 <Variable>MySpace</Variable>
	 <DataType></DataType>
	</DataType>
</Types>
