=== Nitin-Xebia/Training/SOA-WebServices/Sample-Projects/Web-Services/Xml_demo/Schema/ComplexRefElement/personal.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="personnel">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="person" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>		 
	</xs:element>
	<xs:element name="person">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name"/>
				<xs:element ref="email" minOccurs="0" maxOccurs="unbounded"/>				 
				<xs:element name="link" minOccurs="0"/>
			</xs:sequence>	 
		</xs:complexType>
	</xs:element>
	<xs:element name="name">
		<xs:complexType>
			<xs:all>
				<xs:element ref="family"/>
				<xs:element ref="given"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="family" type="xs:string"/>
	<xs:element name="given" type="xs:string"/>
	<xs:element name="email" type="xs:string"/>	 
</xs:schema>

=== Nitin-Xebia/Training/SOA-WebServices/Sample-Projects/XML-Processor/Schema/ComplexRefElement/personal.xml
<?xml version="1.0" encoding="UTF-8"?> 

<personnel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	   xsi:noNamespaceSchemaLocation='personal.xsd'>

  <person>
    <name>
	   <family>Boss</family> 
	   <given>Big</given>
	 </name>
    <email>chief@foo.com</email>    
  </person> 

  <person>    
    <name>
		 <family>
		   Worker
		 </family>
		 <given>
		  One
		  </given>
	</name>     
  </person>

  <person>
    <name><family>Worker</family> <given>Two</given></name>
    <!--email>two@foo.com</email-->    
  </person>    
</personnel>
